(define (problem elevators-prob2)
(:domain elevators)
(:objects f0 f1 f2 f3 f4 - floor p0 p1 p2 p3 p4 - person e0 - elevator)
(:init (elevator-on-floor e0 f4)
       (stopped e0)
       (person-on-floor p0 f0)
       (person-on-floor p1 f0)
       (person-on-floor p2 f0)
       (person-on-floor p3 f0)
       (person-on-floor p4 f1)
)
(:goal (and 
       (person-on-floor p0 f1) 
       (person-on-floor p1 f2) 
       (person-on-floor p2 f3) 
       (person-on-floor p3 f4) 
       (person-on-floor p4 f4)))
)