(define (problem groundproblem) (:domain ground)
(:init
 (robot_at_r0_p2)
 (robot_free_r0)
 (battery_level_r0_five)
 (robot_at_r1_p2)
 (robot_free_r1)
 (battery_level_r1_five)
 (robot_at_r2_p2)
 (robot_free_r2)
 (battery_level_r2_five)
 (pallet_at_b0_p2)
 (pallet_at_b1_p2)
 (pallet_at_b2_p2)
 (pallet_at_b3_p2)
 (position_free_p2)
)
)
