(define (domain ground)
(:requirements :strips)
(:predicates
 (robot_at_r0_p2)
 (robot_free_r0)
 (battery_level_r0_zero)
 (robot_at_r1_p2)
 (robot_free_r1)
 (battery_level_r1_zero)
 (robot_at_r2_p2)
 (robot_free_r2)
 (battery_level_r2_zero)
 (pallet_at_b0_p2)
 (pallet_at_b1_p2)
 (position_free_p2)
 (robot_has_r0_b0)
 (robot_has_r1_b0)
 (robot_has_r2_b0)
 (robot_has_r0_b1)
 (robot_has_r1_b1)
 (robot_has_r2_b1)
)

)
