(define (problem groundproblem) (:domain ground)
(:init
 (robot_at_r0_p2)
 (robot_free_r0)
 (battery_level_r0_seven)
 (robot_at_r1_p2)
 (robot_free_r1)
 (battery_level_r1_seven)
 (pallet_at_b0_p2)
 (pallet_at_b1_p2)
 (pallet_at_b2_p2)
 (pallet_at_b3_p2)
 (position_free_p2)
)
)
