(define (problem elevators-prob1)
(:domain elevators)
(:objects f0 f1 f2 - floor p0 - person e0 - elevator)
(:init (elevator-on-floor e0 f2)
       (stopped e0)
       (person-on-floor p0 f0)
)
(:goal (and (person-on-floor p0 f1) (person-on-floor p0 f2)))
)