(define (problem groundproblem) (:domain ground)
(:init
 (at_truck0_depot0)
 (at_truck1_distributor1)
 (at_hoist0_depot0)
 (available_hoist0)
 (at_hoist1_depot1)
 (available_hoist1)
 (at_pallet0_depot0)
 (at_pallet1_distributor1)
 (at_crate0_depot0)
 (at_crate1_distributor1)
 (clear_pallet0)
 (clear_pallet1)
 (on_crate0_pallet0)
 (on_crate1_pallet1)
)
)
