(define (problem elevators-prob1)
(:domain elevators)
(:objects f0 f1 f2 - floor p0 - person e0 - elevator)
(:init (elevator-on-floor e0 f2)
       (stopped e0)
       (person-on-floor p0 f0)

       (= (dur-enter p0) 1)
       (= (travel-dur e0 f0 f1) 1)
       (= (travel-dur e0 f0 f2) 2)
       (= (travel-dur e0 f1 f0) 1)
       (= (travel-dur e0 f1 f2) 1)
       (= (travel-dur e0 f2 f1) 1)
       (= (travel-dur e0 f2 f0) 2)
)
(:goal (and (person-on-floor p0 f1) (person-on-floor p0 f2)))
)