(define (problem elevators-prob1)
(:domain elevators)
(:objects f0 f1 - floor p0 - passenger e0 - elevator)
(:init (elevator-at e0 f0)
       (elevator-door-open e0)
       (passenger-at p0 f1)
       (= (elevator-duration f0 f1) 1)
       (= (elevator-duration f1 f0) 1)
)
(:goal (passenger-at p0 f0))
(:metric minimize (total-time)))