(define (problem elevators-prob3)
(:domain elevators)
(:objects f0 f1 - floor p0 p1 - passenger e0 e1 - elevator)
(:init (elevator-at e0 f0)
       (elevator-at e1 f1)
       (elevator-door-open e0)
       (passenger-at p0 f1)
       (passenger-at p1 f0)
       (= (elevator-duration f0 f1) 1)
       (= (elevator-duration f1 f0) 1))
(:goal (and (passenger-at p0 f0)
            (passenger-at p1 f1)))
(:metric minimize (total-time)))