(define (domain ground)
(:requirements :strips)
(:predicates
 (started_i0_last_t)
 (ready_i0_t0)
 (started_i1_last_t)
 (ready_i1_t0)
 (not_started_i0_t0)
 (not_treated_i0_t0)
 (not_started_i1_t0)
 (not_treated_i1_t0)
 (next_to_treat_t0_i0)
 (next_to_treat_last_t_i0)
 (not_started_i0_last_t)
 (not_treated_i0_last_t)
 (not_started_i1_last_t)
 (not_treated_i1_last_t)
 (s2_i0_t0_last_t)
 (treated_i0_t0)
 (not_busy)
 (next_to_treat_t0_i1)
 (busy)
 (started_i0_t0)
 (s3_i0_t0_last_t)
 (ready_i0_last_t)
 (s4_i0_t0_last_t)
 (s1_i0_t0_last_t)
)

)
